# Generated by Django 5.0.6 on 2024-07-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='天気の呼び名')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='weather_icons/', verbose_name='アイコン')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='一言があれば')),
                ('date', models.DateField(null=True)),
                ('content', models.TextField(max_length=500, verbose_name='今日の記録')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像')),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily.weather', verbose_name='天気')),
            ],
        ),
    ]
