# Generated by Django 5.0.6 on 2024-08-02 03:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 2), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='一言があれば'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daily.weather', verbose_name='天気'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.entry')),
            ],
        ),
    ]
