# Generated by Django 5.0.6 on 2024-08-02 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_remove_entry_id_remove_entry_image_alter_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
