# Generated by Django 4.2.15 on 2024-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_alter_image_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.ImageField(upload_to='weather_icons/', verbose_name='アイコン'),
        ),
    ]
