# Generated by Django 5.0.6 on 2024-06-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(max_length=255, null=True, verbose_name='メモの追加'),
        ),
    ]
