# Generated by Django 5.0.6 on 2024-07-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_task_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='step',
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='ステップの追加')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.task')),
            ],
        ),
    ]
