# Generated by Django 5.0.6 on 2024-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_remove_task_step_alter_task_slug_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
